language: node_js
node_js:
    - 10
before_script:
    - npm install -g firebase-tools
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: prod
    tags: true
script:
    - firebase deploy --only hosting --token "$FIREBASE_TOKEN"
